version: '3.8'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "yarn install && yarn dev"] # Correct list format

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    volumes:
      - ../clickhouse-data:/var/lib/clickhouse
