name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Step 3: Authenticate Docker with GCP
    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/analytics-test
        docker buildx build --platform linux/amd64 -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # Step 5: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy analytics-test \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/analytics-test \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
